name: Update README with YT Video Thumbnails
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios xml2js

      - name: Get DevOpsea YouTube video thumbnails
        run: node src/js/devopea-get-thumbnails.js > thumbnails.md

      - name: Update README - DevOpsea YT Channel
        run: |
            awk '/<!-- DEVOPSEA-YOUTUBE-VIDEOS-LIST-BEGIN -->/{exit}1' README.md > top.md
            awk '/<!-- DEVOPSEA-YOUTUBE-VIDEOS-LIST-END -->/,0' README.md | tail -n +2 > bottom.md
            cat top.md > README.md
            echo '<!-- DEVOPSEA-YOUTUBE-VIDEOS-LIST-BEGIN -->' >> README.md
            cat thumbnails.md >> README.md
            echo '<!-- DEVOPSEA-YOUTUBE-VIDEOS-LIST-END -->' >> README.md
            cat bottom.md >> README.md
            rm top.md bottom.md

      - name: Get Side Master YouTube video thumbnails
        run: node src/js/sidemaster-get-thumbnails.js > thumbnails.md

        # Add update README for <!-- SIDEMASTER-YOUTUBE-VIDEOS-LIST-BEGIN --> and <!-- SIDEMASTER-YOUTUBE-VIDEOS-LIST-END -->
      - name: Update README - Side Master YT Channel
        run: |
            awk '/<!-- SIDEMASTER-YOUTUBE-VIDEOS-LIST-BEGIN -->/{exit}1' README.md > top.md
            awk '/<!-- SIDEMASTER-YOUTUBE-VIDEOS-LIST-END -->/,0' README.md | tail -n +2 > bottom.md
            cat top.md > README.md
            echo '<!-- SIDEMASTER-YOUTUBE-VIDEOS-LIST-BEGIN -->' >> README.md
            cat thumbnails.md >> README.md
            echo '<!-- SIDEMASTER-YOUTUBE-VIDEOS-LIST-END -->' >> README.md
            cat bottom.md >> README.md
            rm top.md bottom.md

      - name: Commit and push changes
        run: |
            git stash || true
            git fetch origin
            git rebase origin/main
            git stash pop || true
            git diff --quiet && git diff --staged --quiet || {
                git config --local user.email "jersonmartinezsm@gmail.com"
                git config --local user.name "jersonmartinez"
                git commit -am "Update YouTube video thumbnails"
                git push
            }