name: Update README with YT Video Thumbnails

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios xml2js

      - name: Get YouTube video thumbnails
        run: node src/js/get-thumbnails.js > thumbnails.md

      - name: Update README
        run: |
            awk '/<!-- YOUTUBE-VIDEOS-LIST-BEGIN -->/{print;flag=1;next}/<!-- YOUTUBE-VIDEOS-LIST-END -->/{flag=0}flag' README.md > top.md
            awk '/<!-- YOUTUBE-VIDEOS-LIST-END -->/,0' README.md > bottom.md
            cat top.md > README.md
            cat thumbnails.md >> README.md
            tail -n +2 bottom.md >> README.md
            rm top.md bottom.md

      - name: Commit and push changes
        run: |
          git diff --quiet && git diff --staged --quiet || {
            git config --local user.email "jersonmartinezsm@gmail.com"
            git config --local user.name "jersonmartinez"
            git commit -am "Update YouTube video thumbnails"
            git push
          }